#!/usr/bin/env python3
"""Generate words.js for Poople.

Sources (download into the working directory before running):
  enable1.txt  https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt
  20k.txt      https://raw.githubusercontent.com/first20hours/google-10000-english/master/20k.txt

VALID  = every 4-letter ENABLE word, minus BLOCKED. Any of these is an accepted move.
STARTS = familiar words (20k frequency list minus UNFAMILIAR) whose shortest path to "poop" is 3-6 moves,
         and where that shortest path can be walked using familiar words only.
"""
import json
import random
from collections import deque

TARGET = "poop"

BLOCKED = set("""
clit coon cunt dago dyke fags fuck gook homo jism jizz kike kyke paki poon porn quim rape
shit slut spic spik spaz tits twat wank wogs wops gyps cums
""".split())

# Familiar words next to POOP that aren't in the 20k list.
EXTRA_FAMILIAR = {"poop", "coop", "hoop", "goop", "plop", "prop", "pomp", "pooh", "poof", "loop", "pool", "poor"}

# Names, abbreviations, slang and crude words: never a start word, never on a shown path.
UNFAMILIAR = set("""
alan bios brad bras bros cams carl carr chad cobb coca coco cole cory cote deco dell dick
fave fiat gage gimp jill lama lima lira lite loch mack mage mick phat plat poly rick saul
shah shaw soma tele vail wont than that what your from such duly damn crap suck cock butt
prog pima
""".split())


def neighbors(word, words):
    for i in range(4):
        for c in "abcdefghijklmnopqrstuvwxyz":
            n = word[:i] + c + word[i + 1:]
            if n != word and n in words:
                yield n


def distances(words):
    dist = {TARGET: 0}
    queue = deque([TARGET])
    while queue:
        w = queue.popleft()
        for n in neighbors(w, words):
            if n not in dist:
                dist[n] = dist[w] + 1
                queue.append(n)
    return dist


def main():
    valid = {w.strip() for w in open("enable1.txt") if len(w.strip()) == 4} - BLOCKED
    familiar = ({w.strip() for w in open("20k.txt") if w.strip() in valid} | EXTRA_FAMILIAR) - UNFAMILIAR
    full = distances(valid)
    fam = distances(familiar)
    starts = sorted(
        w for w in familiar - {TARGET}
        if 3 <= full.get(w, 99) <= 6 and fam.get(w) == full[w]
    )
    # Fixed shuffle so the daily order is stable but not alphabetical.
    random.Random(20260928).shuffle(starts)
    with open("words.js", "w") as f:
        f.write("// Generated by tools/build_words.py - do not edit by hand.\n")
        f.write("const VALID_WORDS = " + json.dumps(" ".join(sorted(valid))) + ";\n")
        f.write("const FAMILIAR_WORDS = " + json.dumps(" ".join(sorted(familiar))) + ";\n")
        f.write("const START_WORDS = " + json.dumps(starts) + ";\n")
    print(f"{len(valid)} valid, {len(familiar)} familiar, {len(starts)} starts")


if __name__ == "__main__":
    main()
